name: Deploy GitBook to GitHub Pages

on:
  push:
    branches: ['main']

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '10'

    - name: Install GitBook CLI
      run: npm install -g gitbook-cli

    - name: Install dependencies
      run: gitbook install

    - name: Build GitBook
      run: gitbook build

    - name: List files in build directory
      run: ls -al _book

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: gitbook
        path: _book

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: gitbook

    - name: List files in artifact directory
      run: ls -al ./_book

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./_book
